/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import HeroImage from "../../public/assets/hero.jpg";
import Button from "@/components/Button";
import ImageSwitcher from "@/components/ImageSwitcher";
import { motion, useMotionValueEvent } from "framer-motion";
import { useScroll } from "framer-motion"
import { createContext, useEffect, useState } from "react";
import cx from "classnames";
import ToUp from "@/components/ToUp";
import { NextPage } from "next";
import { useGetHomePageData } from "@/hooks";
import { useRouter } from "next/router";
import { getImagesUrl } from "@/utils";
import { client } from "@/utils/contentful";
import Card from "@/components/card";



export async function getStaticProps() {
  const res = await client.getEntries({
    content_type: 'product',
    order: 'sys.createdAt'
  })

const products = res.items.map((entry: any) => {
  return {
    id: entry.sys.id,
    ...entry.fields,

  }
})
  return {
    props: {
      products
    },
  }
}

 const Home:NextPage=(prop:any )=> {
  const {products}=prop
  const {
    hero,showCase
  }=useGetHomePageData(products||[])
  const mainProductId = 1;
   
  const { scrollY} = useScroll()
  const [opacityHero, setopacityHero] = useState(0);
 
  useMotionValueEvent(scrollY, "change", (latest) => {
    const v=latest/800
    setopacityHero(v)
  })
  const router=useRouter()
  return (
    <>
   
      <Head>
        <title>E-Commerce SQLi Formation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="space-y-[120px] relative">
  
        <section 
        style={{backgroundImage:`url(${hero.image})`,
        backgroundPosition:"center",}}
        className={cx("bg-no-repeat w-full h-[90vh] bg-cover  bg-fixed"
        )}>
          <motion.div
          style={{backgroundColor:`rgba(255,255,255,${opacityHero})`,backdropFilter:`blur(${opacityHero*10}px)`}}
          className={cx("h-full w-full  flex flex-col items-center justify-center")}>
        <div className="sticky top-0 py-10  flex flex-col items-center justify-center gap-10">
        <h1 className="text-white text-5xl font-bold drop-shadow-xl">
           {hero.title}
          </h1>
          <Button onClick={()=>{
            router.push(hero.link)
          }}>Shop this item
          </Button>
        </div>
          </motion.div>
        </section>
        <motion.section  className="max-w-[1200px] mx-auto px-4 grid grid-cols-2 gap-[200px] items-stretch ">
          <ImageSwitcher

            title={showCase[1].title}
            images={getImagesUrl(showCase[1].images)}
          />
          <div className="justify-center gap-8 max-w-[360px] flex flex-col h-[700px]">
            <motion.h3
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }}
              className="text-2xl"
            >
              {showCase[1].title}
            </motion.h3>
            <motion.p
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.5 }}
            >
              Sed dictum consequat volutpat. Suspendisse et rutrum elit.
              Pellentesque ante velit, scelerisque eget viverra hendrerit,
              vestibulum a mauris. Mauris eu massa lacus. Nunc pulvinar feugiat
              dolor at porttitor.
            </motion.p>
            <Button
              animation={{
                x: 20,
                delay: 0.1,
              }}
              type="secondary"
              onClick={() => {
                router.push("/product/"+showCase[1].id)
              }}
            >
                Shop this item
              
            </Button>
          </div>
        </motion.section>
        <section className="max-w-[1200px] mx-auto px-4 grid grid-cols-2 gap-[200px] items-stretch ">
          <motion.div 
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }} className="justify-center items-center gap-8 max-w-[360px] flex flex-col h-[700px]  text-center">
            <div className="w-[250px] h-[250px] rounded-full overflow-hidden relative">
              <img
                src="/assets/showCase2_3.jpg"
                alt="showcase"
                className="object-cover"
              />
            </div>
            <p>
              Maecenas mattis libero ut nibh finibus varius. Sed sit amet
              scelerisque urna, et viverra orci.
            </p>
            <Button onClick={
              ()=>{
                router.push("/product/"+showCase[2].id)
              }
            } type="secondary">
                Shop this item
            
            </Button>
          </motion.div>
          <ImageSwitcher
            title={"Two colored"}
            images={getImagesUrl(showCase[2].images)}
          />
        </section>
        <section className="container mx-auto grid grid-cols-2 gap-[30px] px-20">
          <motion.img 
              initial={{y:5,x:-20 }}
              whileInView={{ y: 0, x: 0 }}
              transition={{ duration: 1, }} src="/assets/showCase3_1.jpg" alt="showCase" className="transition-all grayscale hover:grayscale-0"/>

          <motion.img
              initial={{y:10,x:20 }}
              whileInView={{ y: 0, x: 0 }}
            transition={{ duration: 1, }}
          src="/assets/showCase3_2.jpg" alt="showCase" className="transition-all grayscale hover:grayscale-0"/>
        </section>
        <section className="max-w-[1200px] mx-auto px-4 grid grid-cols-2 gap-[200px] items-stretch ">
          <ImageSwitcher
            title={showCase[3].title}
            images={getImagesUrl(showCase[3].images)}
          />
          <div className="justify-center gap-8 max-w-[360px] flex flex-col h-[700px]">
            <h3 className="text-2xl">{
              showCase[3].title
            }</h3>
            <p>
              Sed dictum consequat volutpat. Suspendisse et rutrum elit.
              Pellentesque ante velit, scelerisque eget viverra hendrerit,
              vestibulum a mauris. Mauris eu massa lacus. Nunc pulvinar feugiat
              dolor at porttitor.
            </p>
            <Button type="secondary"
            onClick={()=>{
              router.push("/product/"+showCase[3].id)
            }}
            
            >
                Shop this item
             
            </Button>
          </div>
        </section>
        <section className="flex flex-col items-center justify-center text-center gap-4">
          <h1 className="text-secondary text-3xl font-semibold">
            {hero.title}
          </h1>
          <Button onClick={()=>{
            router.push(hero.link)
          }} type="secondary">Shop this item
          </Button>
        </section>
        <section className="h-[200px] bg-secondary"></section>
      </main>
      <ToUp/>
    </>
  );
}

export default Home;